name: PULL from Target Repo to Copy File to Source Repo using Artifacts

on:
  workflow_dispatch: # Trigger manually

jobs:
  copy-to-source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: Farmers-FIS/fis_pocs_client.git
          ref: master
          token: ${{ secrets.TARGET_REPO_TOKEN }}
      - name: Isolate Target Files
        run: |
          mkdir target-files
          cp python_script.py target-files
          pwd
          ls -l
          ls target-files/
          whoami

      - name: Upload Target Files as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: target-repo
          path: python_script.py  # Specify the files to include          
          
      - name: Download Target Files as Artifact
        uses: actions/download-artifact@v4
        with:
          name: target-repo
          path: target-repo  # Specify the files to include 
          
      - name: Validate target
        run: |
          pwd
          ls -l
          git branch           

      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: rdkworld/dummy_delete.git
          ref: master        

      - name: Validate source
        run: |
          pwd
          ls -l 
          git branch 
          
      - name: Process Files
        run: |
          pwd
          # Access files from the source repo
          ls -l

          # Access files from the target repo
          ls target-files/
          whoami
          
      - name: Commit to Source Repo
        run: |
          ls 
          pwd 
          ls -l
          #cp /home/runner/work/dummy_delete/dummy_delete/python_script.py .
          git config --global user.email "Raghavendra.Kulkarni@farmersinsurance.com"
          git config --global user.name "Raghavendra Kulkarni EMU"
          #echo "Adding a comment" >> copy_to_github.md
          git add .
          git commit -m "Copy file from artifact"
          git push --force https://github.com/rdkworld/dummy_delete.git HEAD:master
