name: PULL from Target Repo to Copy File to Source Repo using Artifacts

on:
  workflow_dispatch: # Trigger manually

jobs:
  copy-to-source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: Farmers-FIS/fis_pocs_client.git
          ref: master
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          
      - name: Validate target
        run: |
          pwd
          ls -l
          git branch
           

      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: rdkworld/dummy_delete.git
          ref: main        

      - name: Validate source
        run: |
          pwd
          ls 
          git branch 
          
      - name: Commit to Source Repo
        run: |
          ls 
          pwd 
          ls -l
          cp /home/runner/work/dummy_delete/python_script.py .
          git config --global user.email "Raghavendra.Kulkarni@farmersinsurance.com"
          git config --global user.name "Raghavendra Kulkarni EMU"
          #echo "Adding a comment" >> copy_to_github.md
          git add .
          git commit -m "Copy file from artifact"
          git push --force https://github.com/rdkworld/dummy_delete.git HEAD:main
